@FilmesApi_HostAddress = http://localhost:5210

POST {{FilmesApi_HostAddress}}/filme/ 
Content-type: application/json
{
    "Titulo": "Piratas do Caribe: O fim do mundo",
    "Genero": "Aventura",
    "Duracao": 250
}
###
GET {{FilmesApi_HostAddress}}/filme
Content-type: application/json

###

GET {{FilmesApi_HostAddress}}/filme/1
Content-type: application/json

###


PUT {{FilmesApi_HostAddress}}/filme/3
Content-type: application/json
{
    "Titulo": "Piratas do Caribe e o Bar da Morte",
    "Genero": "Aventura",
    "Duracao": 250
}
###

PATCH {{FilmesApi_HostAddress}}/filme/3
Content-type: application/json
[{
    "op": "replace",
    "path": "/titulo",
    "value": "Avatar"
}]
###

POST {{FilmesApi_HostAddress}}/endereco/ 
Content-type: application/json
{
"Logradouro":"Rua Joaquim Alves Simões",
"Numero": 3088
}
###

POST {{FilmesApi_HostAddress}}/cinema/ 
Content-type: application/json
{
"Nome":"Alura Cinemas2",
"EnderecoId": 1
}
###
GET {{FilmesApi_HostAddress}}/cinema/ 
Content-type: application/json
###


POST {{FilmesApi_HostAddress}}/sessao/ 
Content-type: application/json
{
"FilmeId":2,
"CinemaId" : 1
}
###
GET {{FilmesApi_HostAddress}}/sessao/ 
Content-type: application/json
###